# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dbb42987ab20b9bcdb360704607eb89553787d6b4b25dc75c4972d0f0f8ac4b09e92c7adc9f9a68d6e6516f173cc794994a8fc6284f9612a69c1ea201222092

test:
  secret_key_base: 589fa7bb65a964a3b63d017c67aededc4ae69eacec231ae07169bd5fb84eaa2bb0045c5f449de77304a753840345d38c58e6c08b8ae55a757210a8d8725379a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
